name: mobile_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  email_validator: ^2.0.1

  english_words: ^4.0.0

  realm: ^1.0.3
  shared_preferences: ^2.0.20
  csv: ^5.0.1
  flutter_login: ^4.1.1
  drift: ^2.8.0
  path_provider: ^2.0.15
  drift_dev: ^2.8.2
  http: ^0.13.6
  flutter_dotenv: ^5.0.2
  firebase_core: ^2.14.0 # common code required for all Firebase Flutter plugins.
  firebase_auth: ^4.6.3 # enables integration with Authentication.
  cloud_firestore: ^4.8.1 # nables access to Firestore data storage.
  provider: ^6.0.5 # enables separation of business logic from display logic.
  firebase_ui_auth: ^1.4.3 # provides a set of widgets and utilities to increase developer velocity with authentication flows.
  go_router: ^8.0.5
  firebase_database: ^10.2.3
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets: 
    - assets/
    - .env
