name: mobile_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  email_validator: ^2.0.1

  english_words: ^4.0.0
  provider: ^6.0.0
  realm: ^1.0.3
  sqflite: ^2.2.6
  shared_preferences: ^2.0.20
  csv: ^5.0.1
  splashscreen: 
  flutter_login: ^4.1.1
  drift: ^2.8.0
  path_provider: ^2.0.15
  sqlite3_flutter_libs: ^0.5.15
  drift_dev: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets: 
    - assets/
