name: mobile_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  email_validator: ^2.0.1


  


  english_words: ^4.0.0
  provider: ^6.0.0
  realm: ^1.0.3
  mongo_dart: ^0.9.1
  sqflite: ^2.2.6
  shared_preferences: ^2.0.20
  csv: ^5.0.1
  splashscreen: 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/
