// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUjLRUuJySLL7qTvK3jddGN-ieG6u1GuU',
    appId: '1:396926858675:web:bff19aa0f1a23204f9c7c6',
    messagingSenderId: '396926858675',
    projectId: 'shopu-16be4',
    authDomain: 'shopu-16be4.firebaseapp.com',
    storageBucket: 'shopu-16be4.appspot.com',
    measurementId: 'G-2C5GBJPC94',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ3GI_CJPbNQ3v7_QEf4Y3_v_NsR4SfDg',
    appId: '1:396926858675:android:79774665f468feedf9c7c6',
    messagingSenderId: '396926858675',
    projectId: 'shopu-16be4',
    storageBucket: 'shopu-16be4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtf30lKkKw7Nw7YgRioikXSGBVo5q4FWg',
    appId: '1:396926858675:ios:4f928b79a8ef72a0f9c7c6',
    messagingSenderId: '396926858675',
    projectId: 'shopu-16be4',
    storageBucket: 'shopu-16be4.appspot.com',
    iosClientId: '396926858675-3qqjqg442qk9ppqh8vrn6rmg34q320ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtf30lKkKw7Nw7YgRioikXSGBVo5q4FWg',
    appId: '1:396926858675:ios:4f928b79a8ef72a0f9c7c6',
    messagingSenderId: '396926858675',
    projectId: 'shopu-16be4',
    storageBucket: 'shopu-16be4.appspot.com',
    iosClientId: '396926858675-3qqjqg442qk9ppqh8vrn6rmg34q320ks.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );
}
